fn main() {
    // Embed the launcher icon into the Windows executable. The icon is
    // generated by packaging/configure.py during production builds; when it is
    // absent (e.g. local development) we simply skip embedding it.
    #[cfg(windows)]
    {
        let icon = "assets/icon.ico";
        if std::path::Path::new(icon).exists() {
            let mut res = winres::WindowsResource::new();
            res.set_icon(icon);
            if let Err(err) = res.compile() {
                println!("cargo:warning=failed to embed Windows icon: {err}");
            }
        }
    }
}
