// DO NOT EDIT THIS FILE. THIS FILE IS AUTOGENERATED BY crates/i18n/build.rs

pub static LANG: std::sync::atomic::AtomicU8 = std::sync::atomic::AtomicU8::new(0);

pub fn set_lang(name: &str) {
    let id = match name {
        "en" => 0,
        "ru" => 1,
        _ => 0,
    };
    LANG.store(id, std::sync::atomic::Ordering::Relaxed);
}

pub mod accounts {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "account_override_section" => Some(account_override_section()),
            "account_section" => Some(account_section()),
            "add_account_section" => Some(add_account_section()),
            "add_elyby" => Some(add_elyby()),
            "add_microsoft" => Some(add_microsoft()),
            "add_offline" => Some(add_offline()),
            "add_suggested_account" => Some(add_suggested_account()),
            "add_telegram" => Some(add_telegram()),
            "no_accounts_yet" => Some(no_accounts_yet()),
            "section" => Some(section()),
            "suggested_account" => Some(suggested_account()),
            "title" => Some(title()),
            _ => None,
        }
    }
    pub fn account_override_section() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Переопределение аккаунта",
            _ => "Account Override",
        }
    }
    pub fn account_section() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Аккаунт",
            _ => "Account",
        }
    }
    pub fn add_account_section() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Добавить аккаунт",
            _ => "Add Account",
        }
    }
    pub fn add_elyby() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Добавить Ely.by",
            _ => "Add Ely.by",
        }
    }
    pub fn add_microsoft() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Добавить Microsoft",
            _ => "Add Microsoft",
        }
    }
    pub fn add_offline() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Добавить офлайн",
            _ => "Add Offline",
        }
    }
    pub fn add_suggested_account() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Добавить рекомендуемый аккаунт",
            _ => "Add Suggested Account",
        }
    }
    pub fn add_telegram() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Добавить Telegram",
            _ => "Add Telegram",
        }
    }
    pub fn no_accounts_yet() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Аккаунты ещё не добавлены.",
            _ => "No accounts have been added yet.",
        }
    }
    pub fn required_provider(provider: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Требуемый провайдер: {provider}"),
            _ => format!("Required provider: {provider}"),
        }
    }
    pub fn section() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Аккаунты",
            _ => "Accounts",
        }
    }
    pub fn suggested_account() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Рекомендуемый аккаунт",
            _ => "Suggested Account",
        }
    }
    pub fn suggested_account_needs(provider: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Для этого инстанса нужен {provider}"),
            _ => format!("This instance needs {provider}"),
        }
    }
    pub fn title() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Аккаунты",
            _ => "Accounts",
        }
    }
}
pub mod auth {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "default_launcher_name" => Some(default_launcher_name()),
            _ => None,
        }
    }
    pub fn continue_in_browser(url: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Продолжите авторизацию в браузере: {url}"),
            _ => format!("Continue authentication in your browser: {url}"),
        }
    }
    pub fn continue_in_browser_with_code(url: String, code: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Продолжите авторизацию в браузере: {url}\nКод: {code}"),
            _ => format!("Continue authentication in your browser: {url}\nCode: {code}"),
        }
    }
    pub fn default_launcher_name() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Potato Launcher",
            _ => "Potato Launcher",
        }
    }
}
pub mod backends {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "add_backend" => Some(add_backend()),
            "add_backend_section" => Some(add_backend_section()),
            "configured" => Some(configured()),
            "configured_backends" => Some(configured_backends()),
            "discovered" => Some(discovered()),
            "local_only" => Some(local_only()),
            "manifest_url_hint" => Some(manifest_url_hint()),
            "no_backends_yet" => Some(no_backends_yet()),
            "not_fetched" => Some(not_fetched()),
            "not_fetched_message" => Some(not_fetched_message()),
            "offline" => Some(offline()),
            "offline_message" => Some(offline_message()),
            "refreshing_message" => Some(refreshing_message()),
            "title" => Some(title()),
            _ => None,
        }
    }
    pub fn add_backend() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Добавить бэкенд",
            _ => "Add Backend",
        }
    }
    pub fn add_backend_section() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Добавить бэкенд",
            _ => "Add Backend",
        }
    }
    pub fn configured() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Настроен",
            _ => "Configured",
        }
    }
    pub fn configured_backends() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Настроенные бэкенды",
            _ => "Configured Backends",
        }
    }
    pub fn discovered() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Обнаружен",
            _ => "Discovered",
        }
    }
    pub fn fetch_failed_title(title: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось загрузить {title}"),
            _ => format!("Failed to fetch {title}"),
        }
    }
    pub fn local_only() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "только локальные",
            _ => "local only",
        }
    }
    pub fn manifest_url_hint() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Введите URL манифеста (http или https)",
            _ => "Enter an http(s) manifest URL",
        }
    }
    pub fn no_backends_yet() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Бэкенды ещё не настроены.",
            _ => "No backends configured yet.",
        }
    }
    pub fn not_fetched() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "не загружено",
            _ => "not fetched",
        }
    }
    pub fn not_fetched_message() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Нажмите «Обновить», чтобы попробовать загрузить этот бэкенд.",
            _ => "Use Refresh to try fetching this backend.",
        }
    }
    pub fn not_fetched_title(title: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("{title} ещё не загружался"),
            _ => format!("{title} has not been fetched"),
        }
    }
    pub fn offline() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "офлайн",
            _ => "offline",
        }
    }
    pub fn offline_message() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Установленные инстансы с этого бэкенда появятся здесь, если они есть локально.",
            _ => "Installed instances from this backend will appear here when known locally.",
        }
    }
    pub fn offline_title(title: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("{title} недоступен"),
            _ => format!("{title} is offline"),
        }
    }
    pub fn published_count(count: usize) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("{count} инстансов"),
            _ => format!("{count} instances"),
        }
    }
    pub fn refreshing_message() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Бэкенд ещё не вернул список инстансов.",
            _ => "The backend has not returned an instance list yet.",
        }
    }
    pub fn refreshing_title(title: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Обновление {title}"),
            _ => format!("Refreshing {title}"),
        }
    }
    pub fn title() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Бэкенды",
            _ => "Backends",
        }
    }
}
pub mod common {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "cancel" => Some(cancel()),
            "close" => Some(close()),
            "default" => Some(default()),
            "details" => Some(details()),
            "dismiss" => Some(dismiss()),
            "error" => Some(error()),
            "info" => Some(info()),
            "local" => Some(local()),
            "off" => Some(off()),
            "on" => Some(on()),
            "refresh" => Some(refresh()),
            "refreshing" => Some(refreshing()),
            "remove" => Some(remove()),
            "retry" => Some(retry()),
            "select" => Some(select()),
            "selected" => Some(selected()),
            "settings" => Some(settings()),
            "success" => Some(success()),
            "warning" => Some(warning()),
            _ => None,
        }
    }
    pub fn cancel() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Отмена",
            _ => "Cancel",
        }
    }
    pub fn close() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Закрыть",
            _ => "Close",
        }
    }
    pub fn default() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "По умолчанию",
            _ => "Default",
        }
    }
    pub fn details() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Подробности",
            _ => "Details",
        }
    }
    pub fn dismiss() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Закрыть",
            _ => "Dismiss",
        }
    }
    pub fn error() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Ошибка",
            _ => "Error",
        }
    }
    pub fn info() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Информация",
            _ => "Info",
        }
    }
    pub fn local() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Локальные",
            _ => "Local",
        }
    }
    pub fn off() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Выкл.",
            _ => "Off",
        }
    }
    pub fn on() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Вкл.",
            _ => "On",
        }
    }
    pub fn refresh() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Обновить",
            _ => "Refresh",
        }
    }
    pub fn refreshing() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Обновление...",
            _ => "Refreshing...",
        }
    }
    pub fn remove() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Удалить",
            _ => "Remove",
        }
    }
    pub fn retry() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Повторить",
            _ => "Retry",
        }
    }
    pub fn select() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Выбрать",
            _ => "Use",
        }
    }
    pub fn selected() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Выбрано",
            _ => "Selected",
        }
    }
    pub fn settings() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Настройки",
            _ => "Settings",
        }
    }
    pub fn success() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Успех",
            _ => "Success",
        }
    }
    pub fn warning() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Предупреждение",
            _ => "Warning",
        }
    }
}
pub mod instances {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "actions" => Some(actions()),
            "add_account" => Some(add_account()),
            "add_account_card" => Some(add_account_card()),
            "any_provider" => Some(any_provider()),
            "confirm_delete" => Some(confirm_delete()),
            "confirm_delete_hint" => Some(confirm_delete_hint()),
            "delete" => Some(delete()),
            "hard_resync" => Some(hard_resync()),
            "install" => Some(install()),
            "jvm_flags_default" => Some(jvm_flags_default()),
            "kill" => Some(kill()),
            "launch_blocked" => Some(launch_blocked()),
            "launching" => Some(launching()),
            "logs" => Some(logs()),
            "no_account_selected" => Some(no_account_selected()),
            "no_instances_hint" => Some(no_instances_hint()),
            "no_instances_yet" => Some(no_instances_yet()),
            "open_instance_folder" => Some(open_instance_folder()),
            "open_latest_launch_log" => Some(open_latest_launch_log()),
            "open_launcher_directory" => Some(open_launcher_directory()),
            "override_suffix" => Some(override_suffix()),
            "play" => Some(play()),
            "play_again" => Some(play_again()),
            "resync" => Some(resync()),
            "runtime" => Some(runtime()),
            "set_flags" => Some(set_flags()),
            "set_memory" => Some(set_memory()),
            "status" => Some(status()),
            "status_available" => Some(status_available()),
            "status_failed" => Some(status_failed()),
            "status_installed" => Some(status_installed()),
            "status_launch_failed" => Some(status_launch_failed()),
            "status_orphaned" => Some(status_orphaned()),
            "status_outdated" => Some(status_outdated()),
            "status_running" => Some(status_running()),
            "update" => Some(update()),
            "used_by_installed" => Some(used_by_installed()),
            _ => None,
        }
    }
    pub fn actions() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Действия",
            _ => "Actions",
        }
    }
    pub fn add_account() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Добавить аккаунт",
            _ => "Add Account",
        }
    }
    pub fn add_account_card() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Добавить аккаунт",
            _ => "Add account",
        }
    }
    pub fn any_provider() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Любой провайдер",
            _ => "Any provider",
        }
    }
    pub fn confirm_delete() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Подтвердить удаление",
            _ => "Confirm Delete",
        }
    }
    pub fn confirm_delete_hint() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Нажмите «Подтвердить удаление», чтобы удалить инстанс с диска.",
            _ => "Click Confirm Delete to remove this instance from disk.",
        }
    }
    pub fn delete() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Удалить",
            _ => "Delete",
        }
    }
    pub fn effective_memory(xmx: u64) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Текущая память: {xmx} МБ"),
            _ => format!("Effective memory: {xmx} MB"),
        }
    }
    pub fn hard_resync() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Жёсткая синхронизация",
            _ => "Hard Resync",
        }
    }
    pub fn install() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Установить",
            _ => "Install",
        }
    }
    pub fn jvm_flags(flags: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Флаги JVM: {flags}"),
            _ => format!("JVM flags: {flags}"),
        }
    }
    pub fn jvm_flags_default() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "по умолчанию",
            _ => "default",
        }
    }
    pub fn kill() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Завершить",
            _ => "Kill",
        }
    }
    pub fn launch_blocked() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Выберите подходящий аккаунт или переопределение аккаунта перед запуском.",
            _ => {
                "Select a compatible account or choose an instance account override before launching."
            }
        }
    }
    pub fn launching() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Запуск",
            _ => "Launching",
        }
    }
    pub fn logs() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Логи",
            _ => "Logs",
        }
    }
    pub fn no_account_selected() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Аккаунт не выбран",
            _ => "No account selected",
        }
    }
    pub fn no_instances_hint() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => {
                "Откройте «Бэкенды», чтобы добавить URL манифеста, или создайте локальный инстанс позже."
            }
            _ => "Open Backends to add a manifest URL, or create a local instance later.",
        }
    }
    pub fn no_instances_yet() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Пока нет инстансов",
            _ => "No instances yet",
        }
    }
    pub fn open_instance_folder() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Открыть папку инстанса",
            _ => "Open Instance Folder",
        }
    }
    pub fn open_latest_launch_log() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Открыть последний лог запуска",
            _ => "Open Latest Launch Log",
        }
    }
    pub fn open_launcher_directory() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Открыть папку лаунчера",
            _ => "Open Launcher Directory",
        }
    }
    pub fn override_suffix() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => ", переопределение",
            _ => ", Override",
        }
    }
    pub fn play() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Играть",
            _ => "Play",
        }
    }
    pub fn play_again() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Играть снова",
            _ => "Play Again",
        }
    }
    pub fn recommended_memory(xmx: u64) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Рекомендуемая память: {xmx} МБ"),
            _ => format!("Recommended memory: {xmx} MB"),
        }
    }
    pub fn resync() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Синхронизировать",
            _ => "Resync",
        }
    }
    pub fn runtime() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Запуск",
            _ => "Runtime",
        }
    }
    pub fn set_flags() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Задать флаги",
            _ => "Set Flags",
        }
    }
    pub fn set_memory() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Задать память",
            _ => "Set Memory",
        }
    }
    pub fn status() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Статус",
            _ => "Status",
        }
    }
    pub fn status_available() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Доступен",
            _ => "Available",
        }
    }
    pub fn status_failed() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Ошибка",
            _ => "Failed",
        }
    }
    pub fn status_installed() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Установлен",
            _ => "Installed",
        }
    }
    pub fn status_launch_failed() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Ошибка запуска",
            _ => "Launch failed",
        }
    }
    pub fn status_no_account(status: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("{status}, нет аккаунта"),
            _ => format!("{status}, no account"),
        }
    }
    pub fn status_orphaned() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Не в каталоге",
            _ => "Orphaned",
        }
    }
    pub fn status_outdated() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Устарел",
            _ => "Outdated",
        }
    }
    pub fn status_running() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Запущен",
            _ => "Running",
        }
    }
    pub fn update() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Обновить",
            _ => "Update",
        }
    }
    pub fn used_by_installed() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Используется установленными инстансами",
            _ => "Used by installed instances",
        }
    }
}
pub mod nav {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "accounts" => Some(accounts()),
            "configure_backends" => Some(configure_backends()),
            _ => None,
        }
    }
    pub fn accounts() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Аккаунты",
            _ => "Accounts",
        }
    }
    pub fn configure_backends() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Настроить бэкенды",
            _ => "Configure backends",
        }
    }
}
pub mod notifications {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "account_removed" => Some(account_removed()),
            "already_launching_or_running" => Some(already_launching_or_running()),
            "cancel_install_before_delete" => Some(cancel_install_before_delete()),
            "enter_offline_nickname" => Some(enter_offline_nickname()),
            "install_already_running" => Some(install_already_running()),
            "install_completed" => Some(install_completed()),
            "instance_deleted" => Some(instance_deleted()),
            "instance_not_installed_locally" => Some(instance_not_installed_locally()),
            "minecraft_exited_successfully" => Some(minecraft_exited_successfully()),
            "minecraft_running" => Some(minecraft_running()),
            "minecraft_terminated" => Some(minecraft_terminated()),
            "offline_nickname_empty" => Some(offline_nickname_empty()),
            "preparing_install" => Some(preparing_install()),
            "selected_account_must_match" => Some(selected_account_must_match()),
            "stop_before_delete" => Some(stop_before_delete()),
            "use_account_selection_for_required" => Some(use_account_selection_for_required()),
            _ => None,
        }
    }
    pub fn account_removed() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Аккаунт удалён",
            _ => "Account removed",
        }
    }
    pub fn added_account(username: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Добавлен аккаунт {username}"),
            _ => format!("Added account {username}"),
        }
    }
    pub fn added_offline_account(username: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Добавлен офлайн-аккаунт {username}"),
            _ => format!("Added offline account {username}"),
        }
    }
    pub fn already_launching_or_running() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Инстанс уже запускается или работает",
            _ => "Instance is already launching or running",
        }
    }
    pub fn authentication_failed(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Ошибка авторизации: {error}"),
            _ => format!("Authentication failed: {error}"),
        }
    }
    pub fn cancel_install_before_delete() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Отмените установку перед удалением инстанса",
            _ => "Cancel the install before deleting this instance",
        }
    }
    pub fn enter_offline_nickname() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Введите офлайн-ник в настройках инстанса",
            _ => "Enter an offline nickname in the instance details",
        }
    }
    pub fn failed_add_backend_url(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось добавить URL бэкенда: {error}"),
            _ => format!("Failed to add backend URL: {error}"),
        }
    }
    pub fn failed_delete_instance(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось удалить инстанс: {error}"),
            _ => format!("Failed to delete instance: {error}"),
        }
    }
    pub fn failed_open_instance_folder(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось открыть папку инстанса: {error}"),
            _ => format!("Failed to open instance folder: {error}"),
        }
    }
    pub fn failed_open_launcher_directory(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось открыть папку лаунчера: {error}"),
            _ => format!("Failed to open launcher directory: {error}"),
        }
    }
    pub fn failed_open_logs(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось открыть логи: {error}"),
            _ => format!("Failed to open logs: {error}"),
        }
    }
    pub fn failed_remove_account(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось удалить аккаунт: {error}"),
            _ => format!("Failed to remove account: {error}"),
        }
    }
    pub fn failed_remove_backend_url(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось удалить URL бэкенда: {error}"),
            _ => format!("Failed to remove backend URL: {error}"),
        }
    }
    pub fn failed_save_account(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось сохранить аккаунт: {error}"),
            _ => format!("Failed to save account: {error}"),
        }
    }
    pub fn failed_save_account_override(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось сохранить переопределение аккаунта: {error}"),
            _ => format!("Failed to save account override: {error}"),
        }
    }
    pub fn failed_save_installed(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось сохранить установленный инстанс: {error}"),
            _ => format!("Failed to save installed instance: {error}"),
        }
    }
    pub fn failed_save_jvm_flags(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось сохранить флаги JVM: {error}"),
            _ => format!("Failed to save JVM flags: {error}"),
        }
    }
    pub fn failed_save_launcher_settings(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось сохранить настройки лаунчера: {error}"),
            _ => format!("Failed to save launcher settings: {error}"),
        }
    }
    pub fn failed_save_memory_override(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось сохранить переопределение памяти: {error}"),
            _ => format!("Failed to save memory override: {error}"),
        }
    }
    pub fn failed_save_offline_account(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось сохранить офлайн-аккаунт: {error}"),
            _ => format!("Failed to save offline account: {error}"),
        }
    }
    pub fn failed_save_refreshed_account(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось сохранить обновлённый аккаунт: {error}"),
            _ => format!("Failed to save refreshed account: {error}"),
        }
    }
    pub fn failed_save_selected_account(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Не удалось сохранить выбранный аккаунт: {error}"),
            _ => format!("Failed to save selected account: {error}"),
        }
    }
    pub fn install_already_running() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Установка уже выполняется",
            _ => "Install is already running",
        }
    }
    pub fn install_completed() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Установка инстанса завершена",
            _ => "Instance install completed",
        }
    }
    pub fn install_failed(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Ошибка установки: {error}"),
            _ => format!("Install failed: {error}"),
        }
    }
    pub fn instance_deleted() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Инстанс удалён",
            _ => "Instance deleted",
        }
    }
    pub fn instance_not_installed_locally() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Инстанс не установлен локально",
            _ => "Instance is not installed locally",
        }
    }
    pub fn launch_failed(error: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Ошибка запуска: {error}"),
            _ => format!("Launch failed: {error}"),
        }
    }
    pub fn minecraft_exited_successfully() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Minecraft успешно завершился",
            _ => "Minecraft exited successfully",
        }
    }
    pub fn minecraft_exited_with_code(code: i32) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Minecraft завершился с кодом {code}"),
            _ => format!("Minecraft exited with code {code}"),
        }
    }
    pub fn minecraft_running() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Minecraft запущен",
            _ => "Minecraft is running",
        }
    }
    pub fn minecraft_terminated() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Minecraft был завершён",
            _ => "Minecraft was terminated",
        }
    }
    pub fn offline_nickname_empty() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Офлайн-ник не может быть пустым",
            _ => "Offline nickname cannot be empty",
        }
    }
    pub fn preparing_install() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Подготовка к установке",
            _ => "Preparing install",
        }
    }
    pub fn selected_account_must_match() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Выбранный аккаунт должен соответствовать провайдеру инстанса",
            _ => "Selected account must match the instance auth provider",
        }
    }
    pub fn stop_before_delete() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Остановите инстанс перед удалением",
            _ => "Stop the instance before deleting it",
        }
    }
    pub fn use_account_selection_for_required() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Используйте выбор аккаунта для провайдера, требуемого инстансом",
            _ => "Use Account selection for accounts from the required provider",
        }
    }
}
pub mod placeholders {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "client_id" => Some(client_id()),
            "client_secret" => Some(client_secret()),
            "jvm_flags" => Some(jvm_flags()),
            "launcher_name" => Some(launcher_name()),
            "manifest_url" => Some(manifest_url()),
            "memory_mib" => Some(memory_mib()),
            "offline_nickname" => Some(offline_nickname()),
            "telegram_auth_base_url" => Some(telegram_auth_base_url()),
            _ => None,
        }
    }
    pub fn client_id() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Client ID",
            _ => "Client ID",
        }
    }
    pub fn client_secret() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Client secret",
            _ => "Client secret",
        }
    }
    pub fn jvm_flags() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Дополнительные флаги JVM",
            _ => "Extra JVM flags",
        }
    }
    pub fn launcher_name() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Имя лаунчера",
            _ => "Launcher name",
        }
    }
    pub fn manifest_url() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "https://example.com/manifest.json",
            _ => "https://example.com/manifest.json",
        }
    }
    pub fn memory_mib() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Память (МиБ)",
            _ => "Memory MiB",
        }
    }
    pub fn offline_nickname() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Офлайн-ник",
            _ => "Offline nickname",
        }
    }
    pub fn telegram_auth_base_url() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Базовый URL авторизации Telegram",
            _ => "Telegram auth base URL",
        }
    }
}
pub mod progress {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "checking_files" => Some(checking_files()),
            "checking_install_files" => Some(checking_install_files()),
            "copying_files" => Some(copying_files()),
            "downloading_files" => Some(downloading_files()),
            "downloading_install_files" => Some(downloading_install_files()),
            "downloading_metadata" => Some(downloading_metadata()),
            "extracting_files" => Some(extracting_files()),
            "extracting_native_libraries" => Some(extracting_native_libraries()),
            "fetching_metadata" => Some(fetching_metadata()),
            "installing" => Some(installing()),
            "installing_java" => Some(installing_java()),
            "java_already_installed" => Some(java_already_installed()),
            _ => None,
        }
    }
    pub fn checking_files() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Проверка файлов",
            _ => "Checking files",
        }
    }
    pub fn checking_install_files() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Проверка файлов установки",
            _ => "Checking install files",
        }
    }
    pub fn copying_files() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Копирование файлов",
            _ => "Copying files",
        }
    }
    pub fn downloading_files() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Загрузка файлов",
            _ => "Downloading files",
        }
    }
    pub fn downloading_install_files() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Загрузка файлов установки",
            _ => "Downloading install files",
        }
    }
    pub fn downloading_metadata() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Загрузка метаданных",
            _ => "Downloading metadata",
        }
    }
    pub fn extracting_files() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Распаковка файлов",
            _ => "Extracting files",
        }
    }
    pub fn extracting_native_libraries() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Распаковка нативных библиотек",
            _ => "Extracting native libraries",
        }
    }
    pub fn fetching_metadata() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Получение метаданных",
            _ => "Fetching metadata",
        }
    }
    pub fn installing() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Установка",
            _ => "Installing",
        }
    }
    pub fn installing_java() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Установка Java",
            _ => "Installing Java",
        }
    }
    pub fn installing_java_version(version: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Установка Java {version}"),
            _ => format!("Installing Java {version}"),
        }
    }
    pub fn java_already_installed() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Java уже установлена",
            _ => "Java is already installed",
        }
    }
}
pub mod providers {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "elyby" => Some(elyby()),
            "microsoft" => Some(microsoft()),
            "offline" => Some(offline()),
            "telegram" => Some(telegram()),
            _ => None,
        }
    }
    pub fn elyby() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Ely.by",
            _ => "Ely.by",
        }
    }
    pub fn microsoft() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Microsoft",
            _ => "Microsoft",
        }
    }
    pub fn offline() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Офлайн",
            _ => "Offline",
        }
    }
    pub fn telegram() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Telegram",
            _ => "Telegram",
        }
    }
    pub fn telegram_with_url(url: String) -> String {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => format!("Telegram ({url})"),
            _ => format!("Telegram ({url})"),
        }
    }
}
pub mod settings {
    pub fn get(key: &str) -> Option<&'static str> {
        match key {
            "hide_after_launch_desc" => Some(hide_after_launch_desc()),
            "hide_after_launch_title" => Some(hide_after_launch_title()),
            "hide_usernames_desc" => Some(hide_usernames_desc()),
            "hide_usernames_title" => Some(hide_usernames_title()),
            "language_desc" => Some(language_desc()),
            "language_english" => Some(language_english()),
            "language_russian" => Some(language_russian()),
            "language_title" => Some(language_title()),
            "title" => Some(title()),
            _ => None,
        }
    }
    pub fn hide_after_launch_desc() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Сворачивать окно лаунчера при запуске Minecraft.",
            _ => "Minimize the launcher window when Minecraft starts.",
        }
    }
    pub fn hide_after_launch_title() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Скрывать лаунчер после запуска",
            _ => "Hide launcher after launch",
        }
    }
    pub fn hide_usernames_desc() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Скрывать строку аккаунта на карточках инстансов.",
            _ => "Hide the account line on instance cards.",
        }
    }
    pub fn hide_usernames_title() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Скрывать имена в карточках",
            _ => "Hide usernames in cards",
        }
    }
    pub fn language_desc() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Выберите язык интерфейса лаунчера.",
            _ => "Choose the launcher interface language.",
        }
    }
    pub fn language_english() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "English",
            _ => "English",
        }
    }
    pub fn language_russian() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Русский",
            _ => "Русский",
        }
    }
    pub fn language_title() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Язык",
            _ => "Language",
        }
    }
    pub fn title() -> &'static str {
        match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {
            1 => "Настройки лаунчера",
            _ => "Launcher Settings",
        }
    }
}
